### ISSUE TITLE
[Question?]ModuleNotFoundError: No module named 'common.logger'

### ISSUE THREAD

**Issue by lfei0** [Scitator/Run-Skeleton-Run#1]
I've got an error as follows. I think that the reason is logger.py is not in common directory. Could the authors fix it?
------------------------------------------------------------------------------------------------------------------------------------
  File "Run-Skeleton-Run/ddpg/model.py", line 12, in <module>
    from common.logger import Logger
ModuleNotFoundError: No module named 'common.logger'

**Comment by Scitator** [comment]
Sorry for the delay.
Thanks to @wassname it fixed. Nevertheless, don't forget to `pip install tensorboardX` now.
